[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
eternity_sc = "3zxFMG7wjw3RNe4fgrZ258ppxWUt4S5b6g2pugkd3jhd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
